name: Example Annotations

on: push

jobs:

  annotate:
    name: example
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "::error file=README.md,line=1::ERR test annotation"
    - run: echo "::notice file=README.md,line=2::NoTiCe test annotation"
    - run: echo "::warning file=README.md,line=3::WARN test annotation"
#     - run: echo "::debug file=README.md,line=4::DeBug test annotation"
    - run: echo "::error ::ERR global test annotation" 
    - run: echo "::warning ::WARN global test annotation"
